# Generated by Django 3.1.7 on 2021-12-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'tentative'), (1, 'cancelled'), (2, 'Confirmed')]),
        ),
    ]
