# Generated by Django 3.1.7 on 2021-12-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_event_teamrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
