# Generated by Django 3.1.7 on 2021-12-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201201_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
